'use strict';
const root=document.querySelector('#app');
let user=null,applications=[],preferences=null,options={stages:[],workplaces:[],types:[]},theme='light',current='Today',query='',stageFilter='All stages';
let renderVersion=0,noticeTimer;
try{theme=localStorage.getItem('milo-theme')==='dark'?'dark':'light';}catch{}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,route,primary=false)=>`<button ${route?`data-route="${escape(route)}"`:''} class="${primary?'primary':'quiet'}">${escape(label)}</button>`;
const input=(label,id,value='',type='text',required=false)=>`<label>${label}<input id="${id}" type="${type}" value="${escape(value)}" ${required?'required':''}></label>`;
const select=(label,id,values,value)=>`<label>${label}<select id="${id}">${values.map(v=>`<option ${v===value?'selected':''}>${escape(v)}</option>`).join('')}</select></label>`;
const area=(label,id,value='',rows=6)=>`<label>${label}<textarea id="${id}" rows="${rows}">${escape(value)}</textarea></label>`;
const value=id=>document.querySelector('#'+id).value;
function notify(message){clearTimeout(noticeTimer);document.querySelector('#notice').textContent=message;noticeTimer=setTimeout(()=>{document.querySelector('#notice').textContent='';},6500);}
function applyTheme(){document.documentElement.dataset.theme=theme;document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.textContent=theme==='dark'?'☀ Light mode':'◐ Dark mode');}
async function api(path,method='GET',body){const response=await fetch('/api'+path,{method,credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok){if(response.status===401&&user){user=null;location.hash='Login';}const error=Error(data.error||'Request failed.');error.status=response.status;throw error;}return data;}
function heading(title,sub,action=''){return `<div class="heading"><div><h1>${escape(title)}</h1><p>${escape(sub)}</p></div>${action}</div>`;}
function shell(content){const routes=['Today','Applications','Opportunities','CV studio','Writing','Role preferences','My account',...(user.role==='admin'?['Members','Invitations']:[])];return `<div class="shell"><header class="masthead"><a class="brand" href="#Today"><span class="mark">↗</span>Milo<span class="brand-note">CAREER WORKSPACE</span></a><div class="account"><button class="theme-toggle" data-theme-toggle></button>${button(user.name,'My account')}<button class="quiet live-signout" data-logout>Sign out</button></div></header><div class="nav-bar"><nav class="live-nav" aria-label="Main navigation">${routes.map(r=>`<button data-route="${r}" class="${current===r?'active':''}" ${current===r?'aria-current="page"':''}>${r}</button>`).join('')}</nav></div><main class="workspace"><div class="workspace-context"><span class="workspace-dot" aria-hidden="true"></span><span class="eyebrow">YOUR PRIVATE WORKSPACE / ${escape(current.toUpperCase())}</span></div>${content}<footer class="live-footer"><span>Milo · Your next chapter</span><span>Saved on your server · Email sync and AI not connected</span></footer></main></div>`;}
function authPage(invite=false){root.innerHTML=`<main class="live-auth"><div class="split"><a class="brand" href="#Login"><span class="mark">↗</span>Milo</a><button class="theme-toggle" data-theme-toggle></button></div><section class="panel"><h1>${invite?'Your next chapter starts here.':'Welcome back.'}</h1><p>${invite?'Accept your private invitation to Milo.':'Sign in to your private career workspace.'}</p>${user&&invite?'<div class="live-warning">You are already signed in. Sign out before accepting an invitation for another account.</div><button data-logout>Sign out</button>':`<form id="auth-form" class="toolkit-form">${invite?input('Your name','auth-name','','text',true):input('Email','auth-email','','email',true)}${input('Password','auth-password','','password',true)}<p>${invite?'Choose a password of 12–128 characters.':'Accounts are invite-only. Ask your administrator for an invitation.'}</p><button class="primary">${invite?'Accept invitation':'Sign in'}</button></form>`}</section></main>`;applyTheme();const form=document.querySelector('#auth-form');if(!form)return;document.querySelector('#auth-password').autocomplete=invite?'new-password':'current-password';if(invite){document.querySelector('#auth-password').minLength=12;document.querySelector('#auth-password').maxLength=128;}form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{const data=await api(invite?'/invitations/accept':'/login','POST',invite?{token:location.hash.slice(8),name:value('auth-name'),password:value('auth-password')}:{email:value('auth-email'),password:value('auth-password')});form.reset();user=data.user;history.replaceState(null,'','#Today');await loadSession();await render('Today');}catch(error){notify(error.message);}finally{b.disabled=false;}});}
async function loadSession(){const [me,records,prefs]=await Promise.all([api('/me'),api('/applications'),api('/preferences')]);user=me.user;options=me;applications=records.applications;preferences=prefs.preferences;}
function today(){const active=applications.filter(a=>['Recruiter screen','Assessment','Interview','Team match','Technical interview','Final round'].includes(a.stage));const due=applications.filter(a=>a.follow_up&&a.follow_up<=new Date().toISOString().slice(0,10)&&!['Rejected','Withdrawn'].includes(a.stage));return heading(`Welcome, ${user.name.split(' ')[0]}.`,'Your applications, documents and next steps in one place.',button('Add application','New application',true))+`<section class="overview-grid live-stats"><div class="overview-stat"><span>Applications</span><strong>${applications.length}</strong><small>Your saved pipeline</small></div><div class="overview-stat"><span>In conversation</span><strong>${active.length}</strong><small>Screening through final round</small></div><div class="overview-stat"><span>Follow-ups due</span><strong>${due.length}</strong><small>Today or earlier · UTC dates</small></div><div class="overview-stat"><span>Offers</span><strong>${applications.filter(a=>a.stage==='Offer').length}</strong><small>Your next chapter</small></div></section><div class="quick-actions">${button('Upload CV','CV studio')}${button('Write a cover letter','Writing')}${button('Set role preferences','Role preferences')}</div><section class="panel"><h2>${due.length?'Follow-ups to review':'Recent applications'}</h2>${applicationRows(due.length?due:applications.slice(0,5))}</section>`;}
function applicationRows(items){return items.length?items.map(a=>`<article class="live-app-row"><div><h3>${escape(a.role)}</h3><p>${escape(a.company)} · ${escape(a.location||'Location unspecified')} · ${escape(a.workplace)}</p><small>${a.salary===null?'Salary not specified':`NZD ${Number(a.salary).toLocaleString()} / year`} · ${escape(a.employment_type)}${a.follow_up?' · Follow up '+escape(a.follow_up):''}</small></div><div class="live-actions"><span class="pill">${escape(a.stage)}</span>${button('Open record','Application/'+a.id)}${button('Write letter','Writing/'+a.id)}</div></article>`).join(''):`<div class="live-empty"><h2>No applications yet</h2><p>Add a job you have applied to, or save an opening to review.</p>${button('Add your first application','New application',true)}</div>`;}
function matchingApplications(){const terms=s=>s.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),p=preferences;return applications.filter(a=>(!p.titles||terms(p.titles).some(t=>a.role.toLowerCase().includes(t)))&&(!p.location||a.location.toLowerCase().includes(p.location.toLowerCase()))&&(p.workplace==='Any'||p.workplace===a.workplace)&&(p.type==='Any'||p.type===a.employment_type)&&(!p.salary||(a.salary===null?p.unknownSalary:a.salary>=p.salary))&&!terms(p.excluded).some(c=>a.company.toLowerCase().includes(c)));}
function listPage(opportunities=false){const candidates=opportunities?matchingApplications():applications;const items=candidates.filter(a=>(a.role+' '+a.company+' '+a.location).toLowerCase().includes(query.toLowerCase())&&(stageFilter==='All stages'||a.stage===stageFilter));return heading(opportunities?'Openings that fit.':'Your application history.',opportunities?'Your saved records filtered by role preferences. Live job search is not connected.':'Search, track stages and keep the evidence in one place.',button(opportunities?'Role preferences':'Add application',opportunities?'Role preferences':'New application',true))+`<section class="panel"><div class="live-toolbar"><input id="application-query" aria-label="Search applications" placeholder="Search role, company or location" value="${escape(query)}"><select id="application-stage" aria-label="Stage filter">${['All stages',...options.stages].map(s=>`<option ${stageFilter===s?'selected':''}>${s}</option>`).join('')}</select></div><p id="live-count">${items.length} matching records</p><div id="live-rows">${applicationRows(items)}</div></section>`;}
function editor(a={},events=[]){const isNew=!a.id;return heading(isNew?'Add an application':a.role,isNew?'Save an opening or record an application.':a.company,button('Back to applications','Applications'))+`<div class="detail-layout"><section class="panel"><form id="application-form" class="toolkit-form">${input('Role','job-role',a.role||'','text',true)}${input('Company','job-company',a.company||'','text',true)}${input('Location','job-location',a.location||'')}${select('Work arrangement','job-workplace',options.workplaces,a.workplace||'Hybrid')}${select('Employment type','job-type',options.types,a.employment_type||'Permanent')}${select('Stage','job-stage',options.stages,a.stage||'Applied')}${input('Annual salary (NZD; leave blank if unknown)','job-salary',a.salary??'','number')}${input('Source','job-source',a.source||'')}${input('Source URL','job-url',a.url||'','url')}${input('Applied on','job-applied',a.applied_at||'','date')}${input('Follow up on','job-followup',a.follow_up||'','date')}${area('Job description','job-description',a.description||'')}${area('Private notes','job-notes',a.notes||'',4)}<button class="primary">Save application</button></form></section><aside class="panel"><h2>Stage history</h2><ul class="live-history">${events.map(x=>`<li>${escape(x.previous_stage?x.previous_stage+' → ':'')}${escape(x.stage)}<br><small>${escape(new Date(x.created_at).toLocaleString())}</small></li>`).join('')||'<li>History begins when you save this record.</li>'}</ul>${a.id?button('Write cover letter','Writing/'+a.id,true):''}<p class="live-note">Changes are saved to your account. Mailbox updates will not be connected until a later milestone.</p></aside></div>`;}
function preferencesPage(){const p=preferences;return heading('Your role preferences.','Filter saved openings and prepare for future connected searches.')+`<section class="panel"><form id="preferences-form" class="toolkit-form">${input('Role titles or keywords (comma separated)','pref-titles',p.titles)}${input('Location contains','pref-location',p.location)}${select('Work arrangement','pref-workplace',['Any',...options.workplaces],p.workplace)}${select('Employment type','pref-type',['Any',...options.types],p.type)}${input('Minimum annual salary (NZD)','pref-salary',p.salary,'number')}<label class="live-check"><input id="pref-unknown" type="checkbox" ${p.unknownSalary?'checked':''}>Include jobs with unknown salary</label>${input('Exclude companies (comma separated)','pref-excluded',p.excluded)}<button class="primary">Save preferences</button></form></section>`;}
function cvPage(data){return heading('Your CV.','Private files and reviewed text, saved in your account.')+`<div class="toolkit-grid"><section class="panel"><h2>Upload a CV</h2><label class="upload-zone">Choose PDF, DOCX or TXT<input id="cv-file" type="file" accept=".pdf,.docx,.txt"></label><p>Up to 10 MB per file; 100 MB per user. PDF/Word text extraction is not connected yet. TXT imports into the editor after upload; save the text separately.</p><p id="upload-status" role="status" class="live-upload-status"></p>${data.documents.map(d=>`<article class="live-document"><div><strong>${escape(d.name)}</strong><p>${Math.ceil(d.size/1024)} KB · ${escape(new Date(d.created_at).toLocaleDateString())}</p></div><div><a class="screen-link" href="/api/documents/${d.id}" download>Download</a> <button class="quiet" data-delete-document="${d.id}">Remove</button></div></article>`).join('')||'<p class="live-note">No files uploaded yet.</p>'}</section><section class="panel"><h2>Reviewed CV text</h2><form id="cv-form" class="toolkit-form">${area('Paste or review your CV text','cv-text',data.text,16)}<button class="primary">Save CV text</button></form>${button('Write cover letter','Writing')}<p class="live-note">This text is not automatically scored. A CV relevance score is not a probability of passing employer screening.</p></section></div>`;}
function writingPage(a,letter){if(!a)return heading('Your writing desk.','Create a custom cover letter for a saved application.')+`<section class="panel live-empty"><h2>Start with a job</h2><p>Add an application so your letter has the correct role and company.</p>${button('Add application','New application',true)}</section>`;const l=letter||{recipient:'Hiring team',tone:'Professional',evidence:'',motivation:'',text:''};return heading('Custom cover letter.',a.role+' · '+a.company)+`<div class="toolkit-grid"><section class="panel"><form id="letter-builder" class="toolkit-form"><label>Application<select id="letter-application">${applications.map(j=>`<option value="${j.id}" ${j.id===a.id?'selected':''}>${escape(j.role+' · '+j.company)}</option>`).join('')}</select></label>${input('Recipient','letter-recipient',l.recipient)}${select('Tone','letter-tone',['Professional','Warm','Concise'],l.tone)}${area('Verified relevant experience','letter-evidence',l.evidence,6)}${area('Why this role and company?','letter-motivation',l.motivation,4)}<button class="primary">Build custom draft</button></form><p>Template-based writing using your supplied evidence. AI generation is not connected. Review every draft.</p>${button('Review your CV','CV studio')}</section><section class="panel"><h2>Your draft</h2><form id="letter-form" class="toolkit-form">${area('Editable cover letter','letter-text',l.text,20)}<div class="live-actions"><button class="primary">Save letter</button><button type="button" class="quiet" data-download-letter>Download TXT</button></div></form><p>Save before switching applications. Each job has its own letter.</p></section></div>`;}
function accountPage(){return heading('My account.','Your private workspace and appearance settings.')+`<section class="panel"><form id="profile-form" class="toolkit-form">${input('Name','profile-name',user.name,'text',true)}<p>${escape(user.email)} · ${user.role==='admin'?'Administrator':'Member'}</p><button class="primary">Save name</button></form><p>Theme preference is saved in this browser. Your applications, documents and letters are saved on the server.</p><p class="live-note">Password recovery and additional sign-in methods are not implemented yet.</p></section>`;}
function adminPage(members,invitations){return current==='Members'?heading('Members.','Membership administration does not grant access to private CVs or applications.',button('Invite member','Invitations',true))+`<section class="panel">${members.map(m=>`<article class="live-app-row"><div><h3>${escape(m.name)}</h3><p>${escape(m.email)}</p></div><span class="pill">${m.role==='admin'?'Administrator':'Member'}</span></article>`).join('')}</section>`:heading('Invite someone to Milo.','Single-use invitation links expire after 72 hours.')+`<section class="panel"><form id="invite-form" class="toolkit-form">${input('Email','invite-email','','email',true)}<button class="primary">Create invitation link</button></form><div id="created-invitation"></div><p>Send the link yourself. Milo does not send invitation emails yet. The invited email is fixed by the invitation.</p></section><section class="panel"><h2>Invitation history</h2>${invitations.map(i=>{const status=i.accepted_at?'Accepted':i.revoked_at?'Revoked':i.expires_at<=Date.now()?'Expired':'Pending';return `<article class="live-app-row"><div><h3>${escape(i.email)}</h3><p>Expires ${escape(new Date(i.expires_at).toLocaleString())}</p></div><div><span class="pill">${status}</span>${status==='Pending'?` <button class="quiet" data-revoke-invitation="${i.id}">Revoke</button>`:''}</div></article>`;}).join('')||'<p class="live-note">No invitations yet.</p>'}</section>`;}
function navigate(route){if(location.hash.slice(1)===encodeURIComponent(route)||decodeURIComponent(location.hash.slice(1))===route)render(route);else location.hash=encodeURIComponent(route);}
function bindForm(id,action){const form=document.querySelector('#'+id);if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const submit=form.querySelector('button[type=submit],button:not([type])');if(submit)submit.disabled=true;try{await action();}catch(error){notify(error.message);}finally{if(submit)submit.disabled=false;}});}
function bindPage(route,a){
 bindForm('application-form',async()=>{const payload={role:value('job-role'),company:value('job-company'),location:value('job-location'),workplace:value('job-workplace'),employment_type:value('job-type'),source:value('job-source'),url:value('job-url'),salary:value('job-salary')===''?null:Number(value('job-salary')),stage:value('job-stage'),applied_at:value('job-applied'),follow_up:value('job-followup'),description:value('job-description'),notes:value('job-notes')};const result=await api(a?.id?'/applications/'+a.id:'/applications',a?.id?'PUT':'POST',payload);notify('Application saved.');navigate('Application/'+result.application.id);});
 bindForm('preferences-form',async()=>{await api('/preferences','PUT',{titles:value('pref-titles'),location:value('pref-location'),workplace:value('pref-workplace'),type:value('pref-type'),salary:Number(value('pref-salary')),unknownSalary:document.querySelector('#pref-unknown').checked,excluded:value('pref-excluded')});notify('Role preferences saved.');navigate('Opportunities');});
 bindForm('cv-form',async()=>{await api('/cv','PUT',{text:value('cv-text')});notify('CV text saved.');});
 bindForm('profile-form',async()=>{const data=await api('/me','PUT',{name:value('profile-name')});user=data.user;await render('My account');notify('Name saved.');});
 bindForm('invite-form',async()=>{const result=await api('/admin/invitations','POST',{email:value('invite-email')});await render('Invitations');document.querySelector('#created-invitation').innerHTML=`<div class="notice"><strong>Copy this private link now</strong><p>The token is only shown when created.</p><a class="invite-link" href="${escape(result.url)}">${escape(result.url)}</a></div>`;notify('Invitation created. Nothing was emailed.');});
 if(a?.id){
  const settings=()=>({recipient:value('letter-recipient').trim(),tone:value('letter-tone'),evidence:value('letter-evidence').trim(),motivation:value('letter-motivation').trim()});
  bindForm('letter-builder',async()=>{const s=settings();if(!s.recipient||!s.evidence)throw Error('Add a recipient and verified experience first.');if(value('letter-text').trim()&&!window.confirm('Replace the current draft? Save it first if you want to keep it.'))return;const greeting=s.tone==='Warm'?'Hello':'Dear',opening=s.tone==='Concise'?'I am applying for':'I am pleased to apply for';document.querySelector('#letter-text').value=[`${greeting} ${s.recipient},`,`${opening} the ${a.role} position at ${a.company}.`,s.evidence,s.motivation,'I would welcome the opportunity to discuss how my experience fits your team’s needs.',`${s.tone==='Warm'?'Best wishes':'Kind regards'},\n${user.name}`].filter(Boolean).join('\n\n');notify('Draft built. Edit and save it when ready.');});
  bindForm('letter-form',async()=>{await api('/applications/'+a.id+'/letter','PUT',{...settings(),text:value('letter-text')});notify('Cover letter saved to this application.');});
 }
 document.querySelector('#letter-application')?.addEventListener('change',e=>navigate('Writing/'+e.target.value));
 const updateList=()=>{query=value('application-query');stageFilter=value('application-stage');const candidates=route==='Opportunities'?matchingApplications():applications,items=candidates.filter(a=>(a.role+' '+a.company+' '+a.location).toLowerCase().includes(query.toLowerCase())&&(stageFilter==='All stages'||a.stage===stageFilter));document.querySelector('#live-count').textContent=items.length+' matching records';document.querySelector('#live-rows').innerHTML=applicationRows(items);};
 document.querySelector('#application-query')?.addEventListener('input',updateList);document.querySelector('#application-stage')?.addEventListener('change',updateList);
 document.querySelector('#cv-file')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const status=document.querySelector('#upload-status');if(!/\.(txt|pdf|docx)$/i.test(file.name)||!file.size||file.size>10*1024*1024){notify('Choose a non-empty PDF, DOCX or TXT up to 10 MB.');return;}e.target.disabled=true;status.textContent='Uploading…';try{const buffer=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<buffer.length;i+=32768)binary+=String.fromCharCode(...buffer.subarray(i,i+32768));const text=file.name.toLowerCase().endsWith('.txt')?await file.text():null;await api('/documents','POST',{name:file.name,base64:btoa(binary)});if(current==='CV studio'&&text!==null&&text.length<=100000){if(!value('cv-text').trim()||window.confirm('Replace the CV text editor with this file’s text?'))document.querySelector('#cv-text').value=text;}if(current!=='CV studio'){notify('Private file uploaded and saved. Review it in CV studio.');return;}status.textContent='File saved. Save reviewed CV text separately before leaving this page.';notify('Private file uploaded and saved.'); // Refresh only the document list without discarding unsaved CV text.
 const typed=value('cv-text');await render('CV studio');document.querySelector('#cv-text').value=typed;document.querySelector('#upload-status').textContent='File saved. Save reviewed CV text separately.';
 }catch(error){status.textContent='Upload failed.';notify(error.message);}finally{e.target.disabled=false;}});
}
async function render(route){const version=++renderVersion;current=route;
 if(route.startsWith('invite=')){authPage(true);return;}
 if(!user){authPage(false);return;}
 root.innerHTML=shell('<section class="panel live-workspace-loading">Loading your saved workspace…</section>');applyTheme();
 try{
  await loadSession();let content,a;
  if(route==='Today')content=today();
  else if(['Applications','Opportunities'].includes(route))content=listPage(route==='Opportunities');
  else if(route==='New application')content=editor();
  else if(route.startsWith('Application/')){const data=await api('/applications/'+route.split('/')[1]);a=data.application;content=editor(a,data.history);}
  else if(route==='Role preferences')content=preferencesPage();
  else if(route==='CV studio')content=cvPage(await api('/cv'));
  else if(route==='Writing'||route.startsWith('Writing/')){a=route.includes('/')?applications.find(j=>j.id===route.split('/')[1]):applications[0];if(route.includes('/')&&!a)throw Error('Application not found.');const data=a?await api('/applications/'+a.id+'/letter'):{letter:null};content=writingPage(a,data.letter);}
  else if(route==='My account')content=accountPage();
  else if(['Members','Invitations'].includes(route)){if(user.role!=='admin')throw Error('Administrator access is required.');const data=await api('/admin/'+(route==='Members'?'members':'invitations'));content=adminPage(data.members||[],data.invitations||[]);}
  else {navigate('Today');return;}
  if(version!==renderVersion)return;root.innerHTML=shell(content);applyTheme();document.title='Milo · '+route.split('/')[0];bindPage(route,a);window.scrollTo(0,0);
 }catch(error){if(version!==renderVersion)return;if(!user)authPage();else root.innerHTML=shell(heading('Unable to open this page.',error.message,button('Back to today','Today')));applyTheme();notify(error.message);}
}
document.addEventListener('click',async e=>{try{
 const themeButton=e.target.closest('[data-theme-toggle]');if(themeButton){theme=theme==='dark'?'light':'dark';try{localStorage.setItem('milo-theme',theme);}catch{}applyTheme();}
 const route=e.target.closest('[data-route]');if(route){e.preventDefault();navigate(route.dataset.route);}
 if(e.target.closest('[data-logout]')){const invitation=location.hash.startsWith('#invite=');await api('/logout','POST',{});user=null;if(!invitation)history.replaceState(null,'','#Login');authPage(invitation);}
 const revoke=e.target.closest('[data-revoke-invitation]');if(revoke&&window.confirm('Revoke this invitation?')){await api('/admin/invitations/'+revoke.dataset.revokeInvitation,'DELETE',{});await render('Invitations');notify('Invitation revoked.');}
 const remove=e.target.closest('[data-delete-document]');if(remove&&window.confirm('Permanently remove this uploaded file?')){const typed=document.querySelector('#cv-text')?.value;await api('/documents/'+remove.dataset.deleteDocument,'DELETE',{});await render('CV studio');if(typed!==undefined)document.querySelector('#cv-text').value=typed;notify('File removed.');}
 if(e.target.closest('[data-download-letter]')){const contents=value('letter-text');if(!contents.trim())throw Error('Write a letter first.');const url=URL.createObjectURL(new Blob([contents],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='Milo-cover-letter.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 }catch(error){notify(error.message);}
});
function routeFromHash(){try{return decodeURIComponent(location.hash.slice(1))||'Today';}catch{return 'Today';}}
window.addEventListener('hashchange',()=>render(routeFromHash()));
(async()=>{applyTheme();try{await loadSession();}catch(error){if(error.status!==401)notify(error.message);}await render(routeFromHash());})();
