// Portable draft workflows. No remote services or credentials are simulated.
const toolkitItems=[['Discovery','Plan searches and capture jobs'],['Watchlists','Save company boards and review openings'],['Writing','Draft job-specific letters and replies'],['Analytics','Inspect stages and source response rates'],['Feature coverage','Audit upstream features and pull requests']];
let capturedJobs=[],watchlists=[],searchPlans=[],writingDrafts={},captureCounter=0;
const supportedSources=['LinkedIn','SEEK','Indeed','Glassdoor','Adzuna','Hiring Cafe','Jobindex','Gradcracker','UKVisaJobs','Startup Jobs','Working Nomads','Golang Jobs','FreeHire / OJCP','Workday','BambooHR','Greenhouse','Manual'];
const featureCoverage=[
 ['Application records and stage board','Browser working','Applications','Notes, follow-ups, stages, documents, salary and linked mail.'],
 ['Gmail / Outlook tracking and review','Manual browser workflow','Email inbox','Live OAuth sync, confidence classification and background jobs require backend. Outlook PR #547; IMAP PR #761 are open.'],
 ['Search pipeline and run history','Planning working','Discovery','Country, sources, budget and presets; external extraction, scheduling, retries and cost tracking require backend.'],
 ['Manual capture / URL ingestion','Pasted-text capture working','Discovery','Validated source URL, deduplication and lifecycle stages. Remote URL extraction and bookmarklet endpoint: open PR #362.'],
 ['Multi-select / bulk lifecycle actions','Browser working','Discovery','Selected captured jobs can move to Ready or Skipped; capped at 100.'],
 ['Global search and keyboard navigation','Partial','Applications','Application search is working; command palette, status aliases and full shortcut set remain pending.'],
 ['Resume Studio / Reactive Resume','Draft only','CV studio','Structured editing, JSON import/export, project policies, Reactive Resume and PDF render services remain pending.'],
 ['Tailored resumes and renderers','Backend required','CV studio','AI tailoring, Tectonic / Typst, PDF cache invalidation, print themes and A4/Letter controls. Paper size PR #762 merged; sidebar theme #549 open.'],
 ['Job-specific ghostwriter','Manual drafts working','Writing','Job requirements included; model streaming, regeneration and providers require backend.'],
 ['Post-application analytics','Browser working','Analytics','Source counts and positive responses; small samples hidden by default. Applied-stage reset respected (merged PR #750).'],
 ['Company watchlists','Manual browser workflow','Watchlists','50-board limit, ignore/unignore and canonical URL deduplication; live refresh and baseline tracking require backend. Limit PR #744 merged.'],
 ['Visa sponsor checks','Backend required','Feature coverage','UK, Canada, Netherlands and US register ingestion, update timestamps and employer matching. Register match cannot promise sponsorship.'],
 ['CV link tracer','Backend required','Feature coverage','Public health-checked redirect service, bot filtering and privacy controls; default off. Clicks cannot prove a person read the CV.'],
 ['AI providers and writing/scoring settings','Backend required','Connections','Provider routing, encrypted keys, model discovery, scoring weights, company exclusions and prompt templates.'],
 ['Passkeys and SSO','Backend required','My account','Open PR #749 WebAuthn and #767 SSO. Milo stays invite-only; automatic SSO account creation must be disabled.'],
 ['Workspace tenancy / administration','UI draft only','My account','Server-enforced tenant isolation, invitations, member roles, backups, retention and admin operations required. Tenant PR #732 and non-admin search #758 merged.'],
 ['Docker / OJCP / mobile capture','Backend required','Feature coverage','Production compose services, persistent storage, API authentication and mobile share capture remain pending.'],
 ['Interview learning plans','Browser working','Interview prep','Milo-specific role-based topics, courses, practice questions and session progress.'],
 ['CV screening likelihood','Not a calibrated probability','CV studio','A relevance score is not a probability of passing employer screening; calibration would require outcome data.']
];
function toolkit(){return head('Career toolkit','Your job search, from discovery to interview readiness.')+`<div class="toolkit-grid">${toolkitItems.map(([route,desc],i)=>`<section class="panel toolkit-card"><span class="toolkit-number">${String(i+1).padStart(2,'0')}</span><h2>${route}</h2><p>${desc}</p>${button('Open '+route+' →',route)}</section>`).join('')}</div>`}
function featurePage(){return head('Feature coverage','Reviewed JobOps main and all 11 open pull requests. Integration work is explicitly tracked.')+`<section class="panel"><p><a href="https://github.com/DaKheera47/job-ops" target="_blank" rel="noopener noreferrer">JobOps repository ↗</a> · <a href="https://github.com/DaKheera47/job-ops/pulls" target="_blank" rel="noopener noreferrer">Upstream pull requests ↗</a></p>${featureCoverage.map(([name,state,route,detail])=>`<article class="coverage-row"><div><h3>${name}</h3><p>${detail}</p></div><div>${pill(state)} ${button('View',route)}</div></article>`).join('')}</section>`}
function discovery(){return head('Discovery','Plan a search or capture an opening. External search services are not connected.')+`<div class="toolkit-grid"><section class="panel"><h2>Search plan</h2><form id="search-plan" class="toolkit-form"><label>Search terms<input id="plan-terms" required placeholder="Delivery Lead, Project Manager"></label><label>Country<select id="plan-country"><option>New Zealand</option><option>Australia</option><option>United Kingdom</option><option>United States</option><option>Canada</option><option>Netherlands</option></select></label><label>Source<select id="plan-source">${supportedSources.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Preset<select id="plan-preset"><option>Balanced</option><option>Fast</option><option>Detailed</option></select></label><label>Result budget<input id="plan-budget" type="number" min="50" max="1000" value="100" required></label><button class="primary">Save search plan</button></form><p>Plans are saved in this session. No search is launched and no credits are spent.</p></section><section class="panel"><h2>Capture a job</h2><form id="job-capture" class="toolkit-form"><label>Role<input id="capture-role" required></label><label>Company<input id="capture-company" required></label><label>Source URL<input id="capture-url" type="url" required placeholder="https://…"></label><label>Paste job description<textarea id="capture-text" required rows="5"></textarea></label><button class="primary">Add to discovered</button></form><p>Paste the description yourself. Milo does not fetch the URL.</p></section></div><section class="panel"><h2>Captured openings</h2><button class="quiet" data-capture-bulk="Ready">Mark selected Ready</button> <button class="quiet" data-capture-bulk="Skipped">Skip selected</button>${capturedJobs.length?capturedJobs.map(j=>`<article class="coverage-row"><label><input type="checkbox" data-capture-select="${j.id}" ${j.selected?'checked':''}> ${escapeHTML(j.role)} · ${escapeHTML(j.company)}</label><div>${pill(j.stage)} <a href="${escapeHTML(j.url)}" target="_blank" rel="noopener noreferrer">Source ↗</a><p>${escapeHTML(j.description)}</p></div></article>`).join(''):'<p>No captured openings yet.</p>'}</section><section class="panel"><h2>Saved plans</h2>${searchPlans.map(p=>`<p>${escapeHTML(p.terms)} · ${p.country} · ${p.source} · ${p.preset} · ${p.budget} results · Planned</p>`).join('')||'<p>No saved search plans.</p>'}</section>`}
function canonicalURL(value){try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return null;u.hash='';for(const k of [...u.searchParams.keys()])if(k.startsWith('utm_'))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch(_){return null}}
function watchlistPage(){return head('Company watchlists','Save up to 50 company career boards. Refresh and alerts require connected extractors.')+`<section class="panel"><form id="watchlist-add" class="toolkit-form"><label>Company<input id="watch-company" required></label><label>Career board URL<input id="watch-url" type="url" required></label><button class="primary">Save board</button></form></section><section class="panel"><h2>Your boards · ${watchlists.length}/50</h2>${watchlists.map((w,i)=>`<article class="coverage-row"><div><h3>${escapeHTML(w.company)}</h3><a href="${escapeHTML(w.url)}" target="_blank" rel="noopener noreferrer">Open career board ↗</a><p>${w.ignored?'Ignored':'Awaiting first connected refresh'} · New-job count unavailable</p></div><button class="quiet" data-watch-toggle="${i}">${w.ignored?'Restore':'Ignore'}</button></article>`).join('')||'<p>No boards saved yet.</p>'}</section>`}
function writingPage(){const j=getJob();return head('Writing desk','Keep a job-specific draft. Text is not sent or generated by AI.')+`<section class="panel"><h2>${escapeHTML(j.role)} · ${escapeHTML(j.company)}</h2><p>Requirements: ${escapeHTML(j.requirements)}</p><p>Select another application to change the writing context.</p>${button('Choose application','Applications')}<form id="writing-form" class="toolkit-form"><label>Letter / recruiter reply<textarea id="writing-text" rows="12" placeholder="Write your draft…">${escapeHTML(writingDrafts[j.id]||'')}</textarea></label><button class="primary">Save draft</button></form></section>`}
function analyticsPage(){const sourceNames=[...new Set(jobs.map(j=>j.source))];const positive=new Set(['Recruiter screen','Assessment','Interview','Team match','Technical interview','Final round','Offer']);return head('Application analytics','Computed from the current sample records. Counts describe this session, not your real history.')+`<section class="panel"><h2>Current stage distribution</h2>${statusOptions.map(stage=>{const n=jobs.filter(j=>j.status===stage).length;return n?`<p>${stage} ${pill(String(n))}</p>`:''}).join('')}</section><section class="panel"><h2>Positive response by source</h2><p>Rejections are excluded from positive responses. Moving back to Applied clears the current positive-response classification. Rates are hidden for fewer than 5 records.</p>${sourceNames.map(source=>{const items=jobs.filter(j=>j.source===source),count=items.filter(j=>positive.has(j.status)).length;return `<article class="coverage-row"><h3>${escapeHTML(source)}</h3><p>${count} positive / ${items.length} applications · ${items.length<5?'Insufficient sample':Math.round(count/items.length*100)+'%'}</p></article>`}).join('')}</section>`}
const toolkitViews={'Career toolkit':toolkit,Discovery:discovery,Watchlists:watchlistPage,Writing:writingPage,Analytics:analyticsPage,'Feature coverage':featurePage};
function bindToolkit(){document.querySelector('#search-plan')?.addEventListener('submit',e=>{e.preventDefault();const terms=document.querySelector('#plan-terms').value.trim(),country=document.querySelector('#plan-country').value,source=document.querySelector('#plan-source').value,preset=document.querySelector('#plan-preset').value,budget=Number(document.querySelector('#plan-budget').value);if(!terms||!supportedSources.includes(source)||!['New Zealand','Australia','United Kingdom','United States','Canada','Netherlands'].includes(country)||!['Balanced','Fast','Detailed'].includes(preset)||!Number.isInteger(budget)||budget<50||budget>1000){notify('Complete the plan with a budget of 50–1000.');return}if(['Gradcracker','UKVisaJobs'].includes(source)&&country!=='United Kingdom'){notify('This source supports the United Kingdom only.');return}searchPlans.unshift({terms,country,source,preset,budget});render('Discovery');notify('Plan saved. No external search was launched.');});document.querySelector('#job-capture')?.addEventListener('submit',e=>{e.preventDefault();const role=document.querySelector('#capture-role').value.trim(),company=document.querySelector('#capture-company').value.trim(),url=canonicalURL(document.querySelector('#capture-url').value),description=document.querySelector('#capture-text').value.trim();if(!role||!company||!url||!description){notify('Enter a role, company, valid HTTP(S) URL and description.');return}if(capturedJobs.some(j=>j.url===url||j.company.toLowerCase()===company.toLowerCase()&&j.role.toLowerCase()===role.toLowerCase())){notify('This opening is already captured.');return}capturedJobs.push({id:'capture-'+(++captureCounter),role,company,url,description,stage:'Discovered',selected:false});render('Discovery');notify('Job captured in this session.');});document.querySelector('#watchlist-add')?.addEventListener('submit',e=>{e.preventDefault();const company=document.querySelector('#watch-company').value.trim(),url=canonicalURL(document.querySelector('#watch-url').value);if(!company||!url){notify('Enter a company and valid HTTP(S) career-board URL.');return}if(watchlists.length>=50||watchlists.some(w=>w.url===url)){notify('Board already saved or the 50-board limit was reached.');return}watchlists.push({company,url,ignored:false});render('Watchlists');});document.querySelector('#writing-form')?.addEventListener('submit',e=>{e.preventDefault();writingDrafts[selectedJob]=document.querySelector('#writing-text').value;render('Writing');notify('Draft saved in this session. Nothing was sent.');});}
function handleToolkit(e){const selected=e.target.closest('[data-capture-select]');if(selected){const j=capturedJobs.find(j=>j.id===selected.dataset.captureSelect);if(j)j.selected=selected.checked;}const bulk=e.target.closest('[data-capture-bulk]');if(bulk&&['Ready','Skipped'].includes(bulk.dataset.captureBulk)){const selectedJobs=capturedJobs.filter(j=>j.selected);if(selectedJobs.length>100){notify('Select at most 100 openings.');return}selectedJobs.forEach(j=>{j.stage=bulk.dataset.captureBulk;j.selected=false});render('Discovery');}const toggle=e.target.closest('[data-watch-toggle]');if(toggle){const w=watchlists[Number(toggle.dataset.watchToggle)];if(w){w.ignored=!w.ignored;render('Watchlists');}}}
